      - name: 6. 推送到vercel分支
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: vercel
          publish_dir: ./dist
          user_name: 'sysfox'
          user_email: 'daihao864@163.com'
          full_commit_message: ${{ github.event.head_commit.message }}
