 name: auto-commit
 on:
  push:
    branches:
    - main
  schedule:
  - cron: "0 2 * * 1-5"
  workflow_dispatch:
 jobs:
   task:
     name: task
     runs-on: ubuntu-latest
     steps:
      - name: add sth to a.txt
        run: |
          echo 'a' >> a.txt
      - name:  commit to Github
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: main
          publish_dir: ./
          user_name: 'sysfox'
          user_email: 'daihao864@163.com'
          full_commit_message: ${{ github.event.head_commit.message }}
